style: apply style guide
God-save-the-carrots/ft_transcendence pull request #68
Opened 2024-02-06 07:22 UTC by veggie-garden

eslint 적용한 코드입니다!

1. style guide는 google style guide를 쓰기로 정했습니다.
2. 현재 프론트 코드들만 linter 적용되어 있습니다. 백엔드에 라이브러리 js 코드가 있으면 아래에 추가해 주세요. https://github.com/God-save-the-carrots/ft_transcendence/blob/4889fa91360f25400ebaa6bf6cadbbb94a82172c/.eslintrc.json#L11
3. @sindydwns `phong lighting`과 `pong game`을 분리하기 위해, `pong`의 의미로 쓰인 `phong`을 수정해주세요.

2024-02-06 07:57 UTC, 42JINAM approved these changes

2024-02-06 09:59 UTC, sindydwns requested changes
three.js 파일과 src/game 안의 파일들은 적용하지 말아주세요. three.js에는 앞으로도 적용하지 않을 것이고 src/game 하위 파일에는 나중에 제가 적용해두겠습니다. 지금 적용해두시면 상당히 많은 충돌이 발생해서 의미 없는 추가 작업만 생길거에요.

2024-02-07 04:10 UTC, 42JINAM commented
게임 페이지에 버그가 있어서 제대로 작동 하지 않습니다. 연신님께 확인을 부탁 드린 상태 입니다.

2024-02-07 05:11 UTC, iijung approved these changes

2024-02-07 06:35 UTC, veggie-garden commented
#70 이 브랜치에 새로 작업했음으로 이 pr은 닫습니다.

2024-02-07 06:35 UTC, closed without merging