Feat/fe rank page
God-save-the-carrots/ft_transcendence pull request #90
Opened 2024-02-15 03:28 UTC by veggie-garden

ranking 페이지 백엔드 api 적용시켰습니다

2024-02-15 03:29 UTC, veggie-garden commented
지금 제 노트북이 이상해서, 머지하시기 전에 잘 구동되는지 한 번 확인해주시면 감사하겠습니다!

2024-02-15 11:52 UTC, 42JINAM commented on frontend/src/components/pages/Rank.js
> +    const msg = `${data.data[0].message}`;
데이터가 제대로 들어가 있지 않습니다.

2024-02-15 11:52 UTC, 42JINAM commented on frontend/src/components/pages/Rank.js
> +            <span class="score">${rating4}</span>
페이징 처리가 필요합니다.

2024-02-15 11:52 UTC, 42JINAM commented on frontend/src/components/pages/Rank.js
> +    const img = `/public/assets/profile/${data.data[0].user.photo_id}.png`;
각 블럭을 눌렀을때 해당 유저의 프로필로 갈 수 있게 url 을 연동 해야 합니다.

2024-02-17 01:55 UTC, 42JINAM requested changes

2024-02-17 01:55 UTC, 42JINAM commented on frontend/src/components/pages/Rank.js
> +            <span class="rank">1</span>
랭크를 리터럴 로 넣는게 아니라 api로 받은 정보를 넣어야 합니다

2024-02-17 01:55 UTC, 42JINAM commented on frontend/src/components/pages/Rank.js
> +        <li class="block mine">
나의 정보에 대해 api 를 별도로 요청 하고 그정보를 넣어야 합니다

2024-02-17 01:56 UTC, 42JINAM commented
월요일에 코드를 전반적으로 한번 같이 보면서 변경할 점에 대해 이야기 해보아용.

2024-02-19 01:23 UTC, veggie-garden commented on frontend/src/components/pages/Rank.js
> +    const msg = `${data.data[0].message}`;
정확히 어느 데이터를 말하는지 잘 모르겠습니다

2024-02-19 02:25 UTC, veggie-garden commented on frontend/src/components/pages/Rank.js
> +    const img = `/public/assets/profile/${data.data[0].user.photo_id}.png`;
#[7e0f914](https://github.com/God-save-the-carrots/ft_transcendence/pull/90/commits/7e0f914b2c18790789245a0a803a94786e8fba88) 에서 해결했습니다

2024-02-19 02:45 UTC, veggie-garden commented on frontend/src/components/pages/Rank.js
> +        <li class="block mine">
추후 공부해서 추가하도록 하겠습니다

2024-02-19 02:45 UTC, veggie-garden commented on frontend/src/components/pages/Rank.js
> +    const msg = `${data.data[0].message}`;
```suggestion
    const msg = `${data.data[0].user.message}`;
```

2024-02-19 05:04 UTC, veggie-garden commented on frontend/src/components/pages/Rank.js
> +    const msg1 = `${data.data[1].message}`;
```suggestion
    const msg1 = `${data.data[1].user.message}`;
```

2024-02-19 05:04 UTC, veggie-garden commented on frontend/src/components/pages/Rank.js
> +    const msg2 = `${data.data[2].message}`;
```suggestion
    const msg2 = `${data.data[2].user.message}`;
```

2024-02-19 05:04 UTC, veggie-garden commented on frontend/src/components/pages/Rank.js
> +    const msg3 = `${data.data[3].message}`;
```suggestion
    const msg3 = `${data.data[3].user.message}`;
```

2024-02-19 05:04 UTC, veggie-garden commented on frontend/src/components/pages/Rank.js
> +    const msg4 = `${data.data[4].message}`;
```suggestion
    const msg4 = `${data.data[4].user.message}`;
```

2024-02-19 06:19 UTC, 42JINAM commented
현재 풀리퀘스트에 다른 파트들의 코드가 포함 되어있습니다. 이거 잘못하면 커밋들이 꼬일 것 같아요. 
차라리 새로 브랜치를 파고, 현재 작업하신 내용을 새로 반영하여서 올려주시는게 조금 더 편할 것 같습니다.

2024-02-19 06:22 UTC, veggie-garden commented
그럼 현재 develop 브랜치를 기준으로 브랜치를 새로 파서 작업하고, 이 pr은 닫겠습니다.

2024-02-19 06:22 UTC, closed without merging